### ISSUE TITLE
Need help : wait for port on 127.0.0.1 till it is in LISTENING mode and get pid

### ISSUE THREAD

**Issue by rahulmr** [danielkrainas/node-netstat#14]
Is it possible to use node-netstat to wait for a port until it is in LISTENING mode.

Actually, I am trying to automate appium start stop process for mobile tests using webdriverio config.

The appium server takes time to start and port to be in listening mode.
If the port is not in listening mode then wdio test runner is not able to connect to it and configurations fails.

So wanted to know if there is anyway I can wait for this port 4723 on 127.0.0.1 and I also want the pid of this port so that I can use windows taskkill /F /PID <PID> /T to terminate it once the process is done.

**Comment by danielkrainas** [comment]
interesting use case. I thought I had some code examples from a similar scenario but my case was reversed; I was seeking an unknown port for a known PID. Other than manually polling with node-netstat with `limit:1` and a filter like `filter: { port: 4723 }`, I don't see any way to achieve this currently. There are a couple possible solutions I can implement though: 

1) add a `watch` option and perform the polling from within the library (prefered) 
2) possibly leverage a switch for netstat. I'll need to investigate netstat options for Windows to see if there is anything that can do this already.

I'll have some time tonight to look deeper into this and come up with the best solution

**Comment by rahulmr** [comment]
Thanks @danielkrainas , looking forward for the enhancement.

**Comment by danielkrainas** [comment]
I've added the `watch` option in [v1.4.0](https://github.com/danielkrainas/node-netstat/releases/tag/v1.4.0) that will continuously run the netstat command until it's been told to stop. You can combine this with the `filter` and `limit` options to achieve what you're trying to do. Here is an example of it's usage where I want to wait for an app to use port 9240:

```js
netstat({
	watch: true,
	limit: 1,
	filter: {
		local: {
			port: 9240
		}
	},

	done: function (err) {
		console.log('done');
	}
}, function (line) {
	// netstat line data, including the PID if it was available 
	return false; // stop processing (the limit option will do this for you if you've reached the limit)
});
```

Sorry this took so long to implement. Enjoy and let me know if there are any problems!

**Comment by rahulmr** [comment]
Great Thanks!

**Comment by rahulmr** [comment]
@danielkrainas Just an update. This is working great for me. I am able to wait for appium server to start. Thanks a lot for your good work.

**Comment by danielkrainas** [comment]
Thank you for the feedback. I'm happy to hear it!
