### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by paxos** [danielkrainas/node-netstat#15]
Your last release seems broken, as this seems not to be valid javascript:
https://github.com/danielkrainas/node-netstat/blob/master/lib/activators.js#L57

**Comment by danielkrainas** [comment]
It is valid javascript, it's ES6 syntax and I'm working on a later NodeJS version atm that must support the feature so it didn't blow up while developing. I'll go through it tonight to downgrade the syntax used and formalize the <=ES5 support in the README. Thanks for the feedback!

**Comment by danielkrainas** [comment]
Available in [v1.4.1](https://github.com/danielkrainas/node-netstat/releases/tag/v1.4.1)

**Comment by paxos** [comment]
Thank you!
