### ISSUE TITLE
pid filter working?

### ISSUE THREAD

**Issue by beyondszine** [danielkrainas/node-netstat#18]
Hey there,

I am trying to run node-netstat as per the example but not able to run on my system.  Rest filter are working.  Can anyone help me out with it?

```
$ npm -v
5.6.0
$ node -v
v8.11.1
```

**Comment by beyondszine** [comment]
Apologies, my error!
I have been passing 'pid' key as string and not as a number.
Node use to get exit and not show an error! gotta add error checking for validity of key:value pairs.

**Comment by danielkrainas** [comment]
Not a problem @beyondszine! I'm glad you figured it out. If you need any other assistance, feel free to open another issue
