### ISSUE TITLE
Implement Synchronous behavior

### ISSUE THREAD

**Issue by JavaScriptDude** [danielkrainas/node-netstat#2]
For those who want to write synchronous based applications, could you add functionality to allow your tool synchronously on demand?

Maybe options.sync=true would be the trigger.

**Comment by danielkrainas** [comment]
Implemented in #3 by ae0cd2026641be4fa860bdd697be2b7a944513a7

**Comment by JavaScriptDude** [comment]
Thanks for implementing this Daniel.

**Comment by danielkrainas** [comment]
No problem, thanks for contributing!
