### ISSUE TITLE
Handler function not being called

### ISSUE THREAD

**Issue by rubpro** [danielkrainas/node-netstat#23]
I'm working on an existing codebase and found that the handler function is not being invoked.
I checked previous issues and noticed that one said set `sync: true` but that didn't work. I'm currently running: `node-netstat: "^1.6.0"` and trying to use it to close a standalone Selenium Server running a webdriver on port 4444 locally. Code snippet below. Greatly appreciate any advice on ways to fix/refactor. 🙏 

    const netstat = require('node-netstat');
    const fkill = require('fkill');

    async function getStopWdPromise() {
        return await new Promise((resolve, reject) => {
            netstat({
                sync: true,
                filter: {
                    protocol: 'tcp',
                    local: {port: 4444, address: null}
                },
                limit: 1,
                done: function (error) {
                   console.log(error) // this gets logged error = null
            }
            }, function (data) {
                console.log(data) // everything in this function does not get logged
                console.log(`Killing WebDriver process with pid ${data.pid}`);
                fkill(data.pid, {force: true});
                setTimeout(function () { console.log('Killed WebDriver process') }, 5000);
                resolve();
            });
        });
    }

**Comment by danielkrainas** [comment]
Hi there! Let's get you straightened out. I don't imagine you want `sync: true` since you are wrapping it for async but that shouldn't cause problems. You might try loosening your filter up and see what data comes through `local: { port: 4444 }`, I suspect your handler isn't being called because a match isn't being made. Try that and let me know if you still have trouble.

**Comment by rubpro** [comment]
That was the problem. Your suggested worked like a charm! Thank you very much!
