### ISSUE TITLE
Return process does not exist message 

### ISSUE THREAD

**Issue by RajeshkannanRamakrishnan** [danielkrainas/node-netstat#27]
small suggestion, when am trying to check particular port number process exists or not. if it does not exist return some message. like: {status:'process not found'}

i used this code 

netstat({
    filter: {
        protocol: 'tcp',
        local: {port:8080}
    },
    limit: 1
}, function (data) {
    console.log(data)
});

**Comment by danielkrainas** [comment]
Thank you for the feedback @RajeshkannanRamakrishnan and I'm sorry to have to shoot you down but I don't see this as a good addition. The error message would depend very much on your intent in using the library. You may be interested in a single process, range of ports, or everything.

This can be easily implemented as a wrapper though. Something similar to this

```js
function processPortScanner (port) {
  return new Promise((resolve, reject) => {
    let found = false

    netstat({
      limit: 1,
      filter: {
        protocol: 'tcp',
        local: { port },
    	},
      done: (err) => {
        if (!err && !found) {
          err = new Error('process not found')
        }

        if (err) {
          reject(err)
        } else {
          resolve()
        }
      },
    }, () => found = true)
  })
}
```
