### ISSUE TITLE
Error Module not found

### ISSUE THREAD

**Issue by FedeTommi** [danielkrainas/node-netstat#35]
Hi,
I have the following error:

ERROR in ./node_modules/node-netstat/lib/netstat.js 9:10-31
Module not found: Error: Can't resolve '../package' in 'C:\Users\...\node_modules\node-netstat\lib'

If I change  '../package' to '../package.json' in line 9 of node_modules/node-netstat/lib/netstat.js it is solved.
Would it be possible to change it? Or do you have any suggestions on how I might solve the problem without having to change files in node_modules?

Thank you in advance!

**Comment by danielkrainas** [comment]
@FedeTommi sorry, I had not been keeping up with this project's issues and PR's. I have added a change in commit 9f289f96aa7f7d674b71c403af0eee593ae44248 to qualify the package import path with the json extension.

**Comment by danielkrainas** [comment]
released in [v1.9.0](https://github.com/danielkrainas/node-netstat/releases/tag/v1.9.0)
