### ISSUE TITLE
wait cmd

### ISSUE THREAD

**Issue by jdcarroll** [danielkrainas/node-netstat#9]
Do you guys have a way to run something like 'netstat -w10' with in node-netstat?

**Comment by jdcarroll** [comment]
I am looking to have a continual stream of packet usage form the server

**Comment by danielkrainas** [comment]
I'm not sure what -w10 does but to answer your question, yes. It's possible to change the arguments for netstat by setting a property on `netstat.commands` and `netstat.parsers`. The output is streamed and processed so a continuous or long running netstat call should continued to be handled by node-netstat.

Here's an example of how to create and use a set of custom commands and arguments by setting the properties and specifying a custom platform when calling netstat.

Check out the builtin parsers to get an idea of how to implement your own:
https://github.com/danielkrainas/node-netstat/blob/master/lib/parsers.js

``` js
netstat.commands.custom1 = { cmd: 'netstat', args: ['-v', '-p', 'tcp'] };

netstat.parsers.custom1 = function (line, callback) {
    // perform custom parsing
};

// and then specify the platform "custom1" to match the name of the parser and command
netstat({
    platform: 'custom1',
    filter: {
        pid: 4123,
        protocol: 'tcp'
    },
    limit: 5
}, function (data) {
    // ....
});
```

**Comment by danielkrainas** [comment]
Closing as answered. If you need anymore help, let me know.
